# Naive Bayes

Naive Bayes is a simple and powerful algorithm for classification.
It is based on Bayes' theorem, which is a fundamental theorem in probability theory.
The algorithm is called "naive" because it makes the assumption that the features are independent of each other, which is not always the case in real-world data.
Despite this simplification, Naive Bayes often performs well in practice, especially for text classification tasks.

In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [5]:
#load data
iris = load_iris()


X = iris.data
y = iris.target

#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Guassian Naive Bayes

In [6]:
#initialize the model
gnb = GaussianNB()

#fit the model
gnb.fit(X_train, y_train)

#predict
y_pred = gnb.predict(X_test)

#Evaluate
print("Accuracy Score: \n" , accuracy_score(y_test, y_pred))
print("Confusion Matrix: \n ", confusion_matrix(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))


Accuracy Score: 
 1.0
Confusion Matrix: 
  [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

